# v2 syntax
version: "3.7"

# Named volumes
volumes:
  library_test-temp-config:
    driver: local
  # ~/.local
  library_test-temp-local:
    driver: local
  library_test-temp-cache:
    driver: local
  # ~/.composer
  library_test-temp-composer:
    driver: local
  # cache
  library_test-redis-data:
    driver: local
  # Database
  library_test-postgres-data:
    driver: local

services:
  # smtp
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "${DOCKER_SMTP_PORT:-31025}:1025"
      - "${DOCKER_WEBMAIL_PORT:-31080}:8025"

  api:
    build:
      context: .
    ports:
      - "${DOCKER_API_HTTP_PORT:-8000}:80"
    environment:
      - XDEBUG_ENABLED=${APP_XDEBUG_ENABLED:-false}
      - OPCACHE_MODE=${APP_OPCACHE_MODE:-disabled}
      - JWT_TTL=720
      - MIGRATE=${APP_MIGRATE:-true}
      - LARAVEL_CACHE=${LARAVEL_CACHE:-false}
    volumes:
      - .:/var/www/app
      - library_test-temp-config:/home/app/.config
      - library_test-temp-cache:/home/app/.cache
      - library_test-temp-local:/home/app/.local
      - library_test-temp-composer:/home/app/.composer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/.healthcheck"]
      interval: 5m
      timeout: 20s
      retries: 10
      start_period: 30s
    links:
      - db
      - cache
    depends_on:
      - db
      - cache

  # REDIS
  cache:
    image: redis:5
    restart: ${DOCKER_RESTART:-always}
    command: --appendonly yes
    volumes:
      - library_test-redis-data:/data
    healthcheck:
        test: ["CMD", "redis-cli","ping"]
        interval: 30s
        timeout: 10s
        retries: 3

  # db
  db:
    image: postgres:13.0-alpine
    restart: "no"
    ports:
      - "${DOCKER_DB_PORT:-6322}:5432"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library
    volumes:
      - library_test-postgres-data:/var/lib/postgresql/data
